### ISSUE TITLE
AI21 App for non-tech people

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#105]
## 💻 What to do

As we are launching AI21 Hackathon for non-tech people with expirience in Marketing, Sales, Art, etc, we'd love to have a Tutorial - How to build an AI App with AI21 Studio if you have complitely no coding background.

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Content generation app
- Meeting notes summarization
- Email writer extention
- Automatic chat replier app

### 🧑‍💻 AI21 Studio
Free accoun is available for everyone. The website - https://www.ai21.com/studio

Available:
- [Fundation Models](https://www.ai21.com/studio/foundation-models)
- [Task-Specific APIs](https://www.ai21.com/studio/task-specific-apis)

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

## 👀 Tech Tutorials Examples
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We wont to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $60 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by shreya50** [comment]
@abdibrokhim hi, do you wanna collaborate on tutorial?

**Comment by abdibrokhim** [comment]
hi, let's
