### ISSUE TITLE
PaLM 2 Tutorial

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#107]
## 💻 What to do
Create an app using PaLM 2 model by google. 

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- AI-powered Virtual Assistant
- Code Review and Autocompletion Tool
- Personalized Education Platform
- Medical Diagnosis and Symptom Checker
- News and Information Aggregator
- Financial Planning and Investment Advisor

### 🧑‍💻 PaLM 2
[PaLM 2](https://lablab.ai/tech/google/palm) model to check.

For the access or any support, please, contact our team via Discord.

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

## 👀 Tech Tutorials Examples
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We wont to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $100 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by feliciien** [comment]
hello, i created new pull request

**Comment by ezzcodeezzlife** [comment]
https://lablab.ai/t/palm2-tutorial-building-character-based-chatbot-app-using-powerful-ai-model
https://lablab.ai/t/palm2-tutorial

@OlesiaZinchenko
