### ISSUE TITLE
How to build a website with AI21 Labs

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#158]
## 💻 What to do

As we are launching AI21 Hackathon for non-tech people with expirience in Marketing, Sales, Art, etc, we'd love to have a Tutorial - How to build a website with AI21 Labs.

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Content generation app
- Meeting notes summarization
- Email writer extention
- Automatic chat replier app

### 🧑‍💻 AI21 Studio
Free accoun is available for everyone. The website - https://www.ai21.com/studio

Available:
- [Fundation Models](https://www.ai21.com/studio/foundation-models)
- [Task-Specific APIs](https://www.ai21.com/studio/task-specific-apis)

If you have any troubles with the access, please, contact Olesia#8335 on Discord

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 Tech Tutorials Examples
**[Beginner's AI tutorial: an introduction to LLM (almost) without coding](https://lablab.ai/t/beginners-introduction-llm-open-ai-low-code)**
**[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)**
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $80 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by abdibrokhim** [comment]
> /attempt #158

hello, man are you working on it right now?

**Comment by septiannugraha** [comment]
> > /attempt #158
> 
> hello, man are you working on it right now?

Hello, I just made a PR that claimed the bounty.
