### ISSUE TITLE
monday.com app using Google Vertex models

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#162]
## 💻 What to do

Write a guide on creation app based on moday AI assistant, for The monday.com AI app hackathon, integrating one of Google Vertex AI models.

Here's the giude on building app with monday AI assistant - https://www.twitch.tv/videos/1844496642 

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Formula generator
- Drief writer
- Posts generator
- Tasks clasification

### 🧑‍💻 monday AI Assistant
The monday AI Assistant is an intelligent virtual assistant designed to enhance interactions and workflows on monday.com. It provides helpful suggestions, improves productivity, and supports various use cases, all powered by artificial intelligence technology.

👉 [Developer documentation](https://developer.monday.com/apps/docs)

### Google Cloud AI models to use
[Imagen by Vertex AI](https://lablab.ai/tech/google/imagen) to check.
[PaLM 2](https://lablab.ai/tech/google/palm) model to check.
[Generative AI Studio](https://lablab.ai/tech/google/generative-ai-studio), check out for more info.

If you have any troubles with the access, please, contact Olesia#8335 on Discord

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 monday.com Tutorials Examples
**[monday.com Tutorial: Your first API call](https://lablab.ai/t/monday-first-api-call)**
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $140 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife Please, check the PR and put the status label

**Comment by ezzcodeezzlife** [comment]
https://github.com/lablab-ai/community-content/pull/202 will probably claim the bounty so please do not attempt
