### ISSUE TITLE
How to create an app with AutoGPT

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#163]
## 💻 What to do
Write a tech tutorial as a showcase on building AI app using AutoGPT.

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Formula generator
- Drief writer
- Posts generator
- Tasks clasification

### 🧑‍💻 AutoGPT
More information on the technology - https://lablab.ai/tech/autogpt 

If you have any troubles with the access, please, contact Olesia#8335 on Discord

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 monday.com Tutorials Examples
[AutoGPT tutorial: how to set up your own AI-bot in under 30 minutes](https://lablab.ai/t/autogpt-tutorial-how-to-set-up-your-own-ai-bot-in-under-30-minutes)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $90 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by septiannugraha** [comment]
@abdibrokhim don't you have an issue to work on already? how about work on that one first?

**Comment by abdibrokhim** [comment]
> @abdibrokhim don't you have an issue to work on already? how about work on that one first?

hello, what did you mean?

**Comment by septiannugraha** [comment]
@abdibrokhim you've already made an attempt on another issue, I believe it's monday.com + Vertex AI.  Instead of making yet another attempt on issue which is currently being worked on by someone else (me), you should work on that one.

**Comment by abdibrokhim** [comment]
> @abdibrokhim you've already made an attempt on another issue, I believe it's monday.com + Vertex AI. Instead of making yet another attempt on issue which is currently being worked on by someone else (me), you should work on that one.

Bro, relax. It is good you were/are working on it, but i also wanted try it and make my contribution to tutorial.

**Comment by abdibrokhim** [comment]
And it was not assigned to you so , it is open to everyone :). No stress bro.

**Comment by septiannugraha** [comment]
> Bro, relax. It is good you were/are working on it, but i also wanted try it and make my contribution to tutorial.

Yeah, I guess I believe that's how attempt works. I just found it kinda strange that you chose to work on issues that are already being worked on. Otherwise, that's an insightful tutorial you wrote😁

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim: To receive payouts, [sign up on Algora](https://console.algora.io/auth/login), link your Github account and connect with Stripe on your dashboard.

**Comment by septiannugraha** [comment]
@ezzcodeezzlife Can you reward my PR? it has already been merged. Thank you 😁
