### ISSUE TITLE
How to create a website with Anthropic's Claude + LangChain integration

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#166]
Create tech tutorial on **How to create a website with Anthropic's Claude + LangChain integration**, as a replication of this one - [ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)

## 💻 What do we expect 
Write a high-quality tech tutorial on usage of the  Anthropic's Claude + integration with LangChain on one of Claude use cases.

Please, use as less ChatGPT as possible. Include code samples. If needed, add graphs.

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

## 🛠 Claude Use Cases
- Customer Service
- Legal
- Coaching
- Search
- Back-office
- Sales

## 🔑 Access to Claude

To get API key, please contact Olesia#8335 on Discord in DM.

## ✅ How will we approve?

Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

## 👀 Tutorials Examples
**[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)**
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $100 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by septiannugraha** [comment]
> > /attempt #166
> 
> hello, bro you are really working on this tutorial right now? in case i will start now. i am c complete it

Yes. I'm working on this one right now. You've already wrote that one before.
