### ISSUE TITLE
Build an app with Synthesia API

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#169]
## 💻 What to do

Write a guide on creation app based on Synthesia API.

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Email Assistant
- Pitch generator
- Website bot

### 🧑‍💻 Synthesia API
[Documentation](https://docs.synthesia.io/docs/getting-started)
[API Templates](https://docs.synthesia.io/docs/get-started-with-templates)

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 Tutorials Examples
[ElevenLabs Tutorial: How to Build your own Podcast Generation app](https://lablab.ai/t/elevenlabs-langchain-tutorial-how-to-create-custom-podcast-generator-streamlit-app)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $80 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by goldzulu** [comment]
@OlesiaZinchenko It looks like the description of the issue doe does not make sense. (referring to google vertex). Should it be a synthesia tutorial linked to Monday.com or Google Vertex?

**Comment by OlesiaZinchenko** [comment]
> @OlesiaZinchenko It looks like the description of the issue doe does not make sense. (referring to google vertex). Should it be a synthesia tutorial linked to Monday.com or Google Vertex?

Thanks, edited! It should be Synthesia + can be other integrations

**Comment by goldzulu** [comment]
@OlesiaZinchenko just so you know. 1) Synthesis required a paid account to access their API. Let me know if you have other arrangements for a free trial/access. 2) Sythesia docs said it's in beta and not being maintained. Thoughts? I can still progress but will have to fork out of pocket to access the API.

**Comment by OlesiaZinchenko** [comment]
Hi @goldzulu! The cost of the monthly subscription can be tipped extra. Please, make sure to mention it while will be making PR
