### ISSUE TITLE
How to use Streamlit to deploy your app for your hackathon project

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#179]
**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 Tutorials Examples
[ElevenLabs Tutorial: How to Build your own Podcast Generation app](https://lablab.ai/t/elevenlabs-langchain-tutorial-how-to-create-custom-podcast-generator-streamlit-app)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $80 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by alhuissi** [comment]
@Mohammad-Noor-debug hey! I see you're writing cool multilingual tutorials, but it seems you're having trouble with the PR  process. Let me know if I can help :)

**Comment by Mohammad-Noor-debug** [comment]
Oh yeah, I work with the team in lablab, i originally wanted to make this tutorial for the participants, so they asked me to make it in Arabic too :), would love some help honestly 😅

**Comment by alhuissi** [comment]
1- Fork https://github.com/lablab-ai/community-content (this will create a copy of the repository on your Github profile)
2- Download the forked repository
3- Create a new branch from the forked repository (you need to know how to use Git https://www.w3schools.com/git/git_remote_fork.asp?remote=github)
4- Add the tutorial to your new branch. Must be in .mdx format.
5- Commit and push your changes to the forked repository on Github
6- Make a Pull Request with the /claim# from your forked repository to the main branch of the original from lablab-ai/community-content

**Comment by Mohammad-Noor-debug** [comment]
Really? I read the requirements and it didn’t mention any mdx format

**Comment by Mohammad-Noor-debug** [comment]
Thank you though

**Comment by alhuissi** [comment]
<img width="1359" alt="Screenshot 2023-06-25 at 18 28 05" src="https://github.com/lablab-ai/community-content/assets/30061055/b4e076a1-a171-498a-afae-83dda1c7dc88">
