### ISSUE TITLE
How to use Streamlit to deploy your app for your hackathon project

### ISSUE THREAD

**Issue by Mohammad-Noor-debug** [lablab-ai/community-content#182]
### **What is Streamlit?** 
[https://streamlit.io](Streamlit) is a free and open-source framework that you can use to rapidly build your own project using Python and Javascript, the framework has a comprehensive library that you can use.

### **How to Build a Streamlit App**

You will need to install streamlit on your preferred code editor, it's simply a step

### **Step 1**
-Open your terminal and type:
`pip install streamlit`
_Install any other library/os, that you want to use
for example Langchain
`pip install langchain`

-In your terminal, and create a new folder named "Streamlit". then create a file inside there called "streamlit_app.py", also if you're using an AI create an "apikey.py" and add the api key in there, and then create a "requirements.txt" file

-Add all the names of the libraries you're using to the requirments.txt file:
 for example:
 `Streamlit==1.23.1`
 `Langchain==1.23.0`
 
 -To check what version of streamlit you're using,  enter in this command in the terminal:
 `streamlit --version`

-Now import the libs you installed into streamlit_app.py:
`import streamlit as st`
-Also import any other os such as:
`from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain, SequentialChain
from langchain.memory import ConversationBufferMemory
from langchain.utilities import WikipediaAPIWrapper`

-and if you have any api-key, import that as well:
`from apikey import apikey`

Now start building your app using Streamlit's framework:

(I'll be using a project I built as an example):
```
os.environ['OPENAI_API_KEY']= apikey     st.title('Marketing 3-In-1 Tool')
prompt = st.text_input('Example')

# template
title_template = PromptTemplate(
    input_variables = ['topic'],
    template='Example {topic}'
)

script_template = PromptTemplate(
    input_variables = ['title'],
    template='Example {title}'
)

seo_template = PromptTemplate(
    input_variables = ['title'],
    template='Example {title}'
)

# Memory
title_memory = ConversationBufferMemory(input_key='topic', memory_key='chat_history')
script_memory = ConversationBufferMemory(input_key='title', memory_key='chat_history')
seo_memory = ConversationBufferMemory(input_key='title', memory_key='chat_history')

     
# llms
llm = OpenAI(temperature=0.9) 
title_chain = LLMChain(llm=llm, prompt=title_template,  output_key='title', memory=title_memory)
script_chain = LLMChain(llm=llm, prompt=script_template, output_key='script', memory=script_memory)
seo_chain = LLMChain(llm=llm, prompt=seo_template, output_key='title', memory=seo_memory)

# Output
if prompt:
    title = title_chain.run(prompt)
    script = script_chain.run(title=title)
    seo = seo_chain.run(title=title)
    st.write(response['title'])
    st.write(response['script'])
    st.write(response['title'])
    
    with st.expander('Description History'):
        st.info(title_memory.buffer)
        
    with st.expander('Title History'):
        st.info(script_memory.buffer)
        
    with st.expander('Seo History'):
        st.info(seo_memory.buffer)
```
### **Side note:** **for the api key file, the format is this:**

`apikey = 'sk-exampleforopenaiapikey123`

### **How to deploy your app/project after you've built it using streamlit's framework**

You will need to use Streamlit's community cloud service, which is free.
All you need to do is:

### **Step 2**
-Make a repository in github and upload all the files you finished up,
 **for a detailed step-by-step tutorial on how to do that please refer to the previous tutorial by fabian called "How to set up a github repo"**
 
- Go to the streamlit's community cloud service website, create an account and navigate to the "Get Started" button

<Img src={https://iili.io/HPMXU2R.png}, alt={website}, caption={Community cloud service website}/>

And you'll see a header called "Your Apps", and a button called "New app"

<Img src={https://iili.io/HPMXhmP.png}, alt={App_URL}, caption={App URL}/>

-Click on the button, and you'll see a header called "Deploy an app"
and four sub-headers consecutively called "Repository" "Branch" "Main file path" and "App URL".

<Img src={https://iili.io/HPMXkBa.png}, alt={Deploy}, caption={Deploy an app}/>

-Go to your GitHub repo and copy the main file path/link address from it, go back to the Streamlit page,  click on "Paste GitHub URL" paste the GitHub URL in the sub-header called "GitHub URL", and choose the name of your domain in "App URL"

<Img src={https://iili.io/HPMX8rv.png}, alt={Github}, caption={Github Repo}/>

<Img src={https://iili.io/HPMXvEJ.png}, alt={Deploy1}, caption={Deploy an app 1}/>

-If you have any API-Key or any configuration file (Use TOML format) that you want to use, click on advanced settings, choose what version of Python you're using, and paste the secret key or any other action that requires configs, in there and click "Save"

<Img src={https://iili.io/HPMXOLg.png}, alt={Advanced_settings}, caption={Advanced settings}/>

<Img src={https://iili.io/HPMXwI1.png}, alt={Advanced_settings1}, caption={Advanced settings 1}/>

<Img src={https://iili.io/HPMXNhF.png}, alt={Advanced_settings2}, caption={Advanced settings 2}/>

-Now all you need to do is click "Deploy!", and your app will be up on the cloud in no time.

Author's username: Mohammad Noor Alkabbani

**Comment by Mohammad-Noor-debug** [comment]
ما هو [https://streamlit.io/](streamlit) ؟
 هو إطار عمل مجاني ومفتوح المصدر يمكنك استخدامه لبناء مشاريعك الخاصة بسرعة باستخدام لغة Python و JavaScript، يحتوي الإطار على مكتبة واسعة يمكنك استخدامها.

كيفية نشر تطبيق/مشروعك بعد الانتهاء من بنائه باستخدام إطار Streamlit؟
ستحتاج إلى استخدام خدمة السحابة الخاصة بمجتمع Streamlit والتي هي مجانية. كل ما عليك فعله هو:
![Streamlit cloud web](https://github.com/lablab-ai/community-content/assets/109039833/ba4ce6ff-a40a-470e-8023-17c2b2a25bb7)

1. الانتقال إلى خدمة السحابة الخاصة بمجتمع Streamlit والتوجه إلى زر "البدء".
2. تسجيل الدخول إلى حساب Streamlit الخاص بك أو إنشاء حساب جديد.


وسيظهر لك عنوان رئيسي بعنوان "تطبيقاتك"، وزر بعنوان "تطبيق جديد".


![App URL](https://github.com/lablab-ai/community-content/assets/109039833/760dce01-a9f4-415a-bb1e-9c56427df97a)

- انقر على الزر "تطبيق جديد"، وسترى عنوانًا يحمل اسم "نشر تطبيق".
- وستظهر لك أربعة عناوين فرعية تتابع بعضها البعض، يحمل العنوان الأول اسم "المستودع"، والثاني "الفرع"، والثالث "مسار الملف الرئيسي"، والرابع "عنوان URL للتطبيق".
![Deploy an app](https://github.com/lablab-ai/community-content/assets/109039833/a5429bbb-4b0a-45aa-b308-69d2ac56107c)


- انتقل إلى مستودع GitHub الخاص بك وانسخ مسار الملف الرئيسي / عنوان الرابط منه ، ثم اعد العودة إلى صفحة Streamlit وانقر فوق "لصق عنوان URL الخاص بـ GitHub" والصق عنوان URL GitHub في العنوان الفرعي المسمى "عنوان URL لـ GitHub".

- حدد اسم نطاقك في العنوان الفرعي المسمى "عنوان URL للتطبيق".

![Github Repo](https://github.com/lablab-ai/community-content/assets/109039833/8289c449-af66-4380-a41c-c8d515ae5bfa)

![Deploy an app1](https://github.com/lablab-ai/community-content/assets/109039833/e6bd9df3-fce0-48fb-b39d-b8dd17ec4190)

- إذا كان لديك أي مفتاح API-Key أو أي ملف تكوين استخدم تنسيق TOML الذي تريد استخدامه، فيمكنك النقر على "إعدادات متقدمة"، واختيار نسخة Python التي تستخدمها، ثم الصق المفتاح السري أو أي إجراء آخر يتطلب تكوينات في المكان المناسب والنقر على "حفظ".

![Advanced settings](https://github.com/lablab-ai/community-content/assets/109039833/274e5358-ed79-426a-9c06-43119382be7f)

![Advanced settings1](https://github.com/lablab-ai/community-content/assets/109039833/34a6d5df-e7c4-4757-af0c-367cf272d213)

![Advanced settings2](https://github.com/lablab-ai/community-content/assets/109039833/57092f83-3fc6-4588-a098-2d3929e20a68)

- الآن كل ما عليك فعله هو النقر فوق "نشر"، وستتم عملية نشر التطبيق الخاص بك على السحابة في وقت قصير.

**Comment by Mohammad-Noor-debug** [comment]
[https://drive.google.com/drive/folders/1-tyLtqoJP3PU2ug6vFLw5yGQkPb5BKSm?usp=drive_link](Tutorial vids for both arabic and english)

**Comment by alhuissi** [comment]
the claim must be done in a PR to the main branch of lablab-ai/community-content . Here are the guidelines: https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md

**Comment by Mohammad-Noor-debug** [comment]
How did you claim yours? It’s through a pull request right? How do you do that?

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife could you please check this tutorials + video as well - we will publish it as a second for the issue

**Comment by OlesiaZinchenko** [comment]
@Mohammad-Noor-debug  Please, remake

**Comment by Mohammad-Noor-debug** [comment]
### Title: **"LabLab Streamlit Tutorial: How to use Streamlit to deploy your app for your hackathon project"**

### **Description: "How to use streamlit to deploy your app on their community cloud service for your hackathon project"**
### **Author's Username: Mohammad Noor Alkabbani**

### **What is Streamlit?** 
[https://streamlit.io](Streamlit) is a free and open-source framework that you can use to rapidly build your own project using Python and Javascript, the framework has a comprehensive library that you can use.



### **How to Build a Streamlit App**

You will need to install streamlit on your preferred code editor, it's simply a step

### **Step 1**
-Open your terminal and type:
`pip install streamlit`
_Install any other library/os, that you want to use
for example Langchain
`pip install langchain`

-In your terminal, and create a new folder named "Streamlit". then create a file inside there called "streamlit_app.py", also if you're using an AI create an "apikey.py" and add the api key in there, and then create a "requirements.txt" file

-Add all the names of the libraries you're using to the requirments.txt file:
 for example:
 `Streamlit==1.23.1`
 `Langchain==1.23.0`
 
 -To check what version of streamlit you're using,  enter in this command in the terminal:
 `streamlit --version`


-Now import the libs you installed into streamlit_app.py:
`import streamlit as st`
-Also import any other os such as:
`from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain, SequentialChain
from langchain.memory import ConversationBufferMemory
from langchain.utilities import WikipediaAPIWrapper`

-and if you have any api-key, import that as well:
`from apikey import apikey`

Now start building your app using Streamlit's framework:

(I'll be using a project I built as an example):
```
os.environ['OPENAI_API_KEY']= apikey     st.title('Marketing 3-In-1 Tool')
prompt = st.text_input('Example')

# template
title_template = PromptTemplate(
    input_variables = ['topic'],
    template='Example {topic}'
)

script_template = PromptTemplate(
    input_variables = ['title'],
    template='Example {title}'
)

seo_template = PromptTemplate(
    input_variables = ['title'],
    template='Example {title}'
)

# Memory
title_memory = ConversationBufferMemory(input_key='topic', memory_key='chat_history')
script_memory = ConversationBufferMemory(input_key='title', memory_key='chat_history')
seo_memory = ConversationBufferMemory(input_key='title', memory_key='chat_history')

     
# llms
llm = OpenAI(temperature=0.9) 
title_chain = LLMChain(llm=llm, prompt=title_template,  output_key='title', memory=title_memory)
script_chain = LLMChain(llm=llm, prompt=script_template, output_key='script', memory=script_memory)
seo_chain = LLMChain(llm=llm, prompt=seo_template, output_key='title', memory=seo_memory)

# Output
if prompt:
    title = title_chain.run(prompt)
    script = script_chain.run(title=title)
    seo = seo_chain.run(title=title)
    st.write(response['title'])
    st.write(response['script'])
    st.write(response['title'])
    
    with st.expander('Description History'):
        st.info(title_memory.buffer)
        
    with st.expander('Title History'):
        st.info(script_memory.buffer)
        
    with st.expander('Seo History'):
        st.info(seo_memory.buffer)
```
### **Side note:** **for the api key file, the format is this:**

`apikey = 'sk-exampleforopenaiapikey123`

### **How to deploy your app/project after you've built it using streamlit's framework**

You will need to use Streamlit's community cloud service, which is free.
All you need to do is:

### **Step 2**
-Make a repository in github and upload all the files you finished up,
 **for a detailed step-by-step tutorial on how to do that please refer to the previous tutorial by fabian called "How to set up a github repo"**
 
- Go to the streamlit's community cloud service website, create an account and navigate to the "Get Started" button

<Img src={https://iili.io/HPMXU2R.png}, alt={website}, caption={Community cloud service website}/>

And you'll see a header called "Your Apps", and a button called "New app"

<Img src={https://iili.io/HPMXhmP.png}, alt={App_URL}, caption={App URL}/>


-Click on the button, and you'll see a header called "Deploy an app"
and four sub-headers consecutively called "Repository" "Branch" "Main file path" and "App URL".

<Img src={https://iili.io/HPMXkBa.png}, alt={Deploy}, caption={Deploy an app}/>



-Go to your GitHub repo and copy the main file path/link address from it, go back to the Streamlit page,  click on "Paste GitHub URL" paste the GitHub URL in the sub-header called "GitHub URL", and choose the name of your domain in "App URL"

<Img src={https://iili.io/HPMX8rv.png}, alt={Github}, caption={Github Repo}/>

<Img src={https://iili.io/HPMXvEJ.png}, alt={Deploy1}, caption={Deploy an app 1}/>



-If you have any API-Key or any configuration file (Use TOML format) that you want to use, click on advanced settings, choose what version of Python you're using, and paste the secret key or any other action that requires configs, in there and click "Save"

<Img src={https://iili.io/HPMXOLg.png}, alt={Advanced_settings}, caption={Advanced settings}/>

<Img src={https://iili.io/HPMXwI1.png}, alt={Advanced_settings1}, caption={Advanced settings 1}/>

<Img src={https://iili.io/HPMXNhF.png}, alt={Advanced_settings2}, caption={Advanced settings 2}/>

-Now all you need to do is click "Deploy!", and your app will be up on the cloud in no time.


Author's username: Mohammad Noor Alkabbani
