### ISSUE TITLE
ElevenLabs Tutorial: Create your own chatbot (LLM + ElevenLabs)

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#210]
## 💻 What to do

Write a showcase of Chatbot creation with ElevenLabs model + any LLM (like GPT-4. Cohere, AI21 Studio)

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 💡 Some ideas
- Medical Chatbot
- Virtual friend chat
- Website Voice Assistant 

### 🧑‍💻 ElevenLab
Register and create your account here - https://beta.elevenlabs.io

Please, contact us on Discord in case of any questions or extra credits request.

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 Tutorials Examples
[ElevenLabs Tutorial: How to Build your own Podcast Generation app](https://lablab.ai/t/elevenlabs-langchain-tutorial-how-to-create-custom-podcast-generator-streamlit-app)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $80 for complited and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by abdibrokhim** [comment]
PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`. For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip



Did you guys face this kind of issue using in ElevenLabs?

**Comment by septiannugraha** [comment]
@ezzcodeezzlife  @OlesiaZinchenko Please re-open this issue and you can close it as completed after rewarding my PR! Thank you..!
