### ISSUE TITLE
ElevenLabs Tutorial: Create stories with Voice AI from ElevenLabs

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#211]
## 💻 What to do

Write a showcase of Create voiceover for your existing or new story. For this, use any LLM model or public domain audiobook + ElevenLabs tech.

**_Please, avoid using chatGPT for text. Include code samples. If needed, add graphs._**

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

### 🧑‍💻 ElevenLab
Register and create your account here - https://beta.elevenlabs.io

Please, contact us on Discord in case of any questions or extra credits request.

## ✅ How will we approve?
Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

You will het paid automatically once your PR will be merged.

## 👀 Tutorials Examples
[ElevenLabs Tutorial: How to Build your own Podcast Generation app](https://lablab.ai/t/elevenlabs-langchain-tutorial-how-to-create-custom-podcast-generator-streamlit-app)
[ChatGPT tutorial: How to create a website with ChatGPT](https://lablab.ai/t/chatgpt-tutorial-how-to-create-a-website-with-chatgpt)
[AI Agents tutorial: How to use and build AI Agents](https://lablab.ai/t/ai-agents-tutorial-how-to-use-and-create-them)

👉🏼 Check more tutorials on lablab.ai/t

## 📹 Video-Tutorial
We want to tip $50 extra for those builders that want to create video tutorial based on the written one. 
P.S. You don't have to be the Tutorial author to make a video.

Some examples:
- Shorter - https://youtu.be/ysUFk87I-Vk
- Longer - https://youtu.be/TAeED8yJAUI

## 💰 Reward
We will bounty $60 for completed and approved this Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by septiannugraha** [comment]
@OlesiaZinchenko , can you please re-open this issue? it's been claimed already. Thank you.

**Comment by septiannugraha** [comment]
> @septiannugraha Do you want to use the same tutorial? Or it will be fine to you to focus on others ElevenLabs tutorials available?

The same topic as this one would be fine. Also.. can you up the bounty? I'm about to run out of my Starter plan due to all the testing of projects for my previous tutorials. An extra $20 would be nice. I promise it will be good. Thank you! 😄

**Comment by abdibrokhim** [comment]
> > @septiannugraha Do you want to use the same tutorial? Or it will be fine to you to focus on others ElevenLabs tutorials available?
> 
> The same topic as this one would be fine. Also.. can you up the bounty? I'm about to run out of my Starter plan due to all the testing of projects for my previous tutorials. An extra $20 would be nice. I promise it will be good. Thank you! 😄

bro, there enough other tutorials available with ElevenLabs you attempting for

**Comment by septiannugraha** [comment]
> > > @septiannugraha Do you want to use the same tutorial? Or it will be fine to you to focus on others ElevenLabs tutorials available?
> > 
> > 
> > The same topic as this one would be fine. Also.. can you up the bounty? I'm about to run out of my Starter plan due to all the testing of projects for my previous tutorials. An extra $20 would be nice. I promise it will be good. Thank you! 😄
> 
> bro, there enough other tutorials available with ElevenLabs you attempting for

I've run out of ElevenLabs tutorials to attempt as of now, besides, I've already planned to finish this one but unfortunately it's already been claimed. If it's possible to re-open the issue, why don't I give it a try? 😎

**Comment by OlesiaZinchenko** [comment]
> > > > @septiannugraha Do you want to use the same tutorial? Or it will be fine to you to focus on others ElevenLabs tutorials available?
> > > 
> > > 
> > > The same topic as this one would be fine. Also.. can you up the bounty? I'm about to run out of my Starter plan due to all the testing of projects for my previous tutorials. An extra $20 would be nice. I promise it will be good. Thank you! 😄
> > 
> > 
> > bro, there enough other tutorials available with ElevenLabs you attempting for
> 
> I've run out of ElevenLabs tutorials to attempt as of now, besides, I've already planned to finish this one but unfortunately it's already been claimed. If it's possible to re-open the issue, why don't I give it a try? 😎

I don't think it's a good idea to write 2 on the same topic. In case you have some others use cases - feel free to let me know and I will create another issue. I don't really want to duplicate the use case - better focus on quality

**Comment by septiannugraha** [comment]
> I don't think it's a good idea to write 2 on the same topic. In case you have some others use cases - feel free to let me know and I will create another issue. I don't really want to duplicate the use case - better focus on quality

That would be great! I can always think of other use cases. Thank you!
