### ISSUE TITLE
Anthropic Claude + LangChain Tutorial

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#30]
Create tech tutorial on **building simple app utilizing Anthropic's Claude + integration with LangChain**

## 💻 What do we expect 
Write a high-quality tech tutorial on usage of the  Anthropic's Claude + integration with LangChain on one of Claude use cases.

Please, use as less chatGPT as possible. Include code samples. If needed, add graphs.

Here's the delailed Guide and Requirements on [creating Tech Tutorials](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md)

## 🛠 Claude Use Cases

- Customer Service
- Legal
- Coaching
- Search
- Back-office
- Sales

## 🔑 Access to Claude

To get API key, please contact Olesia#8335 on Discord in DM.

## ✅ How will we approve?

Our SEO specialist and developer from the lablab.ai team will review your tutorial. We will contact you with feedback and requested changes if needed.

## 💰 Reward 

We will bounty $30 for complited and approved Tech Tutorial

Want to chat on great content ideas or have questions? Contact me, Olesia#8335 on Discord😉

**Comment by OlesiaZinchenko** [comment]
@abdibrokhim The tutorial already on review ;)

**Comment by septiannugraha** [comment]
Seems open to me
![image](https://github.com/lablab-ai/community-content/assets/26893133/f57d1e6c-0b76-4167-9c48-aa5df4459329)

**Comment by abdibrokhim** [comment]
bro, it always like these, even rewarded ones

**Comment by septiannugraha** [comment]
I guess I'll need to consult @OlesiaZinchenko about this.

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife Please, check the PR and put the status label
