### ISSUE TITLE
Building an research article summarizer and related articles using ARXIV, GPT3.5, Annoy and Sentence BERT  

### ISSUE THREAD

**Issue by Raghavan1988** [lablab-ai/community-content#361]
I am writing a tutorial on how to build a 
1. scholarly article summarizer, 
2. find related articles
3. propose an application 
Technologies: Annoy, Langchain, GPT3.5, Sentence BERT

**Comment by ezzcodeezzlife** [comment]
@Raghavan1988 ok, nice. No need to create an issue for this, just make a PR and then we will check it. Thank you for contributing! 🚀
