### ISSUE TITLE
Cohere Rerank Model: The Solution For Search AI Application

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#363]
## 💻 What to do

We require a beginner-friendly tutorial to help newcomers lean and start building with 2 cohere models:
- [Rerank](https://lablab.ai/tech/cohere/rerank)
- [Generate](https://lablab.ai/tech/cohere/generate)

Make it as descriptive as possible. Add code samples. **Add the part of deployment of the app on demo platforms as Vercel / Redis / Streamlit.**

Please avoid using ChatGPT for text generation. Focus on original content with descriptive details and code samples as needed.

Refer to our [Tutorial Guidelines](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md) for requirements.

## Tutorials Examples 

**You also can refer to any tutorials created on lablab.ai - in your tutorial.**

Some of Cohere tutorials that will be mentioned over the same Hackathon:
* [Cohere tutorial](https://lablab.ai/t/cohere-semantic-search): Semantic Search with Cohere
* [Cohere tutorial](https://lablab.ai/t/cohere-text-embedder): Text embedder with Cohere
* [Cohere tutorial](https://lablab.ai/t/cohere-chatbot): Q&A chatbot with heart from Cohere

## 🔑 Tech details and access

In case you would face any issues in terms of the usage of the model, or accessing the features you need for tutorial, credits, Cohere team support, please, contact Olesia#8335 via Discord, or olesia@newnative.ai via email.

## ✅ Checking and publishing process

Our SEO specialist and developer from the lablab.ai team will review the tutorial draft. We'll provide feedback on any changes needed before final approval.

### 🔗  Links

While writing tutorial, you might have links to share with AI builders. To make sure your Tech Tutorial will got the highest visibility possible, please, mark all external links (the one that not refer readers to lablab.ai, as "nofollow". _It's needed for better SEO optimization of the Tutorial._

Here's how to do it. Pasting links inside of the texture following anchor tag with the attribute:
`<a href="https://example.com" rel="nofollow">Link to Example.com</a>`

**Hard DEADLINE: October 20th, 2023**

**Comment by Sanchay-T** [comment]
@OlesiaZinchenko?

**Comment by Mattral** [comment]
That's interesting!
