### ISSUE TITLE
Falcon LLMs Models: In-depth Tutorials

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#365]
## 💻 What to do

We require a detailed tutorial on use cases, best practices and setting up 3 of Falcon LLMs Models. Use the following models:
* [Falcon-180B](https://huggingface.co/spaces/tiiuae/falcon-180b-demo)
* [Falcon-40B](https://huggingface.co/tiiuae/falcon-40b)
* [Falcon-7B](https://huggingface.co/tiiuae/falcon-7b)

**[Falcon Tech Page](https://lablab.ai/tech/tiiuae/falcon-llm)**

Make it as descriptive as possible. Add code samples. 

Please avoid using ChatGPT for text generation. Focus on original content with descriptive details and code samples as needed.

Refer to our [Tutorial Guidelines](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md) for requirements.

## 🔑 Tech details and access

In case you would face any issues in terms of the usage of the model, or accessing the features you need for tutorial, credits, Cohere team support, please, contact Olesia#8335 via Discord, or olesia@newnative.ai via email.

## ✅ Checking and publishing process

Our SEO specialist and developer from the lablab.ai team will review the tutorial draft. We'll provide feedback on any changes needed before final approval.

### 🔗  Links

While writing tutorial, you might have links to share with AI builders. To make sure your Tech Tutorial will got the highest visibility possible, please, mark all external links (the one that not refer readers to lablab.ai, as "nofollow". _It's needed for better SEO optimization of the Tutorial._

Here's how to do it. Pasting links inside of the texture following anchor tag with the attribute:
`<a href="https://example.com" rel="nofollow">Link to Example.com</a>`

**Hard DEADLINE: October 20th, 2023**

**Comment by OlesiaZinchenko** [comment]
@abdibrokhim This tutorial on you. Here's more detailed task

**Comment by abdibrokhim** [comment]
> @abdibrokhim This tutorial on you. Here's more detailed task

Thanks! Already made PR
