### ISSUE TITLE
autogpt-tutorial-building-ai-agent-powered-research-assistant-app.mdx

### ISSUE THREAD

**Issue by thebestbradley** [lablab-ai/community-content#367]
At the end of the tutorial you tell the user they can access the interface on port 3000, but according to the repositroies documentation it is actually port 8000. This has been verified on my local install.

**Comment by abdibrokhim** [comment]
> At the end of the tutorial you tell the user they can access the interface on port 3000, but according to the repositroies documentation it is actually port 8000. This has been verified on my local install.

Hello @thebestbradley it is not necessary, you may any time change port number to your desired one). cheers

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim could you please open a PR to fix this? 

Thank you @thebestbradley for noticing!

**Comment by abdibrokhim** [comment]
> @abdibrokhim could you please open a PR to fix this?
> 
> Thank you @thebestbradley for noticing!

sure

**Comment by abdibrokhim** [comment]
> At the end of the tutorial you tell the user they can access the interface on port 3000, but according to the repositroies documentation it is actually port 8000. This has been verified on my local install.

may i ask you take screenshot actual issue and your verfication?

**Comment by ezzcodeezzlife** [comment]
@thebestbradley

**Comment by ezzcodeezzlife** [comment]
wil close this for now @thebestbradley feel free to respond or reopen this issue :)
