### ISSUE TITLE
TruLens + LangChain Tutorial: Chatbot Application With Advanced Output

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#397]
## 💻 The Brief

AI Tech to use/discover:
- [TruLens](https://lablab.ai/tech/truera/trulens)
- [TruEra](https://lablab.ai/tech/truera)
- [TruLens GitHub](https://github.com/truera/trulens)
- [TruLens Quickstart](https://github.com/truera/trulens/blob/main/trulens_eval/examples/quickstart/langchain_quickstart.ipynb)
- TruLens User Case Guides:
  * [Any LLM App](https://www.trulens.org/trulens_eval/use_cases_any/)
  * [RAGs](https://www.trulens.org/trulens_eval/use_cases_rag/)
  * [LLM Agents](https://www.trulens.org/trulens_eval/use_cases_agent/)
  * [Dev to Prod](https://www.trulens.org/trulens_eval/use_cases_production/)

*That is the challenges that will be used over the Hackathon. With this tutorial we'd love to help people understand whole circle of app development for the Hackathon.*

### The Plan and Structure of the Tutorial (recommended)

1. Introduction to Trules and its capabilities.
2. Development of a showcase application utilizing Google Vertex, with an emphasis on rapid iteration.
3. Identifying opportunities for enhancement through TruEra.
4. After prototyping your application, establish an evaluation suite using TruEra to gauge its performance based on the key metrics relevant to your specific use case.
5. Detect and address underperforming areas in your application, enabling iterative improvements.
6. Conclusion

**Use case:** Chatbot

___

Make it as descriptive as possible. Add code samples, images, videos (if needed). If you need additional designs - let us know - we are happy to prepare some.

Focus on original, personalized content with descriptive details and code samples as needed. Feel free to use your personal author style, with wording "In this tutorial I will show you...", "this time I want to show you..." etc.

Refer to our [Tutorial Guidelines](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md) for requirements.

## Tutorials / Tech Pages To Link in the article (in the list we mention recommended keywords for links)

* [TruLens](https://lablab.ai/tech/truera/trulens)
* [TruEra](https://lablab.ai/tech/truera)

## 🔑 Tech details and access

In case you would face any issues in terms of the usage of the model, or accessing the features you need for tutorial, credits, Cohere team support, please, contact Olesia#8335 via Discord, or olesia@newnative.ai via email.

## ✅ Checking and publishing process

Our SEO specialist and developer from the lablab.ai team will review the tutorial draft. We'll provide feedback on any changes needed before final approval.

### 🔗  Links

Pasting links, that are not for "lablab.ai/" inside of the text, follow anchor tag with the attribute:
`<a href="https://example.com" rel="nofollow">Link to Example.com</a>`

Bounty $80

**Hard DEADLINE: November 8th, 2023**

**Comment by OlesiaZinchenko** [comment]
Hi @poojanvig! I see that this tutorial already taken. To avoid competition, may you, please, consider other open bounties?

**Comment by OlesiaZinchenko** [comment]
Hi @alhuissi Do you have the timeline estimation? Will you be able to deliver the article on time? Any support needed?

**Comment by OlesiaZinchenko** [comment]
@poojanvig I'm not sure about this tutorial >> https://github.com/lablab-ai/community-content/issues/398

If you can make it on time - feel free to take this one, since we haven't got estimation from the community writer that took this tutorial. What do you think?

**Comment by alhuissi** [comment]
@OlesiaZinchenko Hi, I'm on it. I'll have it ready in a couple of hours.

**Comment by Mattral** [comment]
> 🎉🎈 @alhuissi has been awarded **$80**! 🎈🎊
That's Impressive! Bravo
