### ISSUE TITLE
TruLens + Google Vertex AI Tutorial: TruLens Helping Build RAG Applications

### ISSUE THREAD

**Issue by OlesiaZinchenko** [lablab-ai/community-content#398]
## 💻 The Brief

AI Tech to use/discover:
- [TruLens](https://lablab.ai/tech/truera/trulens)
- [TruEra](https://lablab.ai/tech/truera)
- [TruLens GitHub](https://github.com/truera/trulens)
- [TruLens Quickstart](https://github.com/truera/trulens/blob/main/trulens_eval/examples/quickstart/langchain_quickstart.ipynb)
- TruLens User Case Guides:
  * [Any LLM App](https://www.trulens.org/trulens_eval/use_cases_any/)
  * [RAGs](https://www.trulens.org/trulens_eval/use_cases_rag/)
  * [LLM Agents](https://www.trulens.org/trulens_eval/use_cases_agent/)
  * [Dev to Prod](https://www.trulens.org/trulens_eval/use_cases_production/)

*That is the challenges that will be used over the Hackathon. With this tutorial we'd love to help people understand whole circle of app development for the Hackathon.*

### The Plan and Structure of the Tutorial (recommended)

1. Introduction to Trules and its capabilities.
2. Development of a showcase application utilizing Google Vertex, with an emphasis on rapid iteration.
3. Identifying opportunities for enhancement through TruEra.
4. After prototyping your application, establish an evaluation suite using TruEra to gauge its performance based on the key metrics relevant to your specific use case.
5. Detect and address underperforming areas in your application, enabling iterative improvements.
6. Conclusion

**Use case:** RAG

___

Make it as descriptive as possible. Add code samples, images, videos (if needed). If you need additional designs - let us know - we are happy to prepare some.

Focus on original, personalized content with descriptive details and code samples as needed. Feel free to use your personal author style, with wording "In this tutorial I will show you...", "this time I want to show you..." etc.

Refer to our [Tutorial Guidelines](https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md) for requirements.

## Tutorials / Tech Pages To Link in the article (in the list we mention recommended keywords for links)

* [TruLens](https://lablab.ai/tech/truera/trulens)
* [TruEra](https://lablab.ai/tech/truera)

## 🔑 Tech details and access

In case you would face any issues in terms of the usage of the model, or accessing the features you need for tutorial, credits, Cohere team support, please, contact Olesia#8335 via Discord, or olesia@newnative.ai via email.

## ✅ Checking and publishing process

Our SEO specialist and developer from the lablab.ai team will review the tutorial draft. We'll provide feedback on any changes needed before final approval.

### 🔗  Links

Pasting links, that are not for "lablab.ai/" inside of the text, follow anchor tag with the attribute:
`<a href="https://example.com" rel="nofollow">Link to Example.com</a>`

Bounty $80

**Hard DEADLINE: November 20th, 2023**

**Comment by OlesiaZinchenko** [comment]
Hi @sura-genesis! Great to see you attempt! Could you please briefly estimate the time you will need as well as technologies you might need access you - maybe we can support some of them.

**Comment by sura-genesis** [comment]
hello olesia

Thank you for your message. Hopefully I will finish the documentation by
the 5th of  November. and I need to have to access to the google vertex AI
also I wish to have mentor whom I can contact when I get stack in the way.

**Comment by OlesiaZinchenko** [comment]
Hi @sura-genesis Do you have any updates on the tutorial delivery date? Any help needed maybe?

**Comment by sura-genesis** [comment]
hello, I have been working on the tutorial and it is good progress but I
need help to access the google vertex. I could not sign up for the site
because it requirescredit card details. can you assist me?

**Comment by adamrayed** [comment]
Can I attempt this?

**Comment by sura-genesis** [comment]
Ya you can.

**Comment by OlesiaZinchenko** [comment]
Hi @sura-genesis Could you please share with me your email for the Google Vertex AI access? I will share the access with you via email.

**Comment by sura-genesis** [comment]
***@***.***

**Comment by sura-genesis** [comment]
Hello OlesiaZinchenko,
Thank you for your response. you can use the above email.

I have been reading and investiging about trulens so I can guaranty you I
can submit the tutorial with in 2 - 3 days.

**Comment by OlesiaZinchenko** [comment]
> Hello OlesiaZinchenko, Thank you for your response. you can use the above email. I have been reading and investiging about trulens so I can guaranty you I can submit the tutorial with in 2 - 3 days. On Wed, 15 Nov 2023, 5:10 pm surafel nigusie, ***@***.***> wrote:
> […](#)

Thank you @sura-genesis! Just sent you an email, please confirm you received the details. Thanks!

**Comment by sura-genesis** [comment]
Yes I do.
